openapi: "3.0.0"

info:
  title: Пример документации
  description: Описание примера документации
  version: "1.0"

servers:
  - url: "http://localhost:80/api/"
  - url: "http://localhost:81/api/"
  - url: "http://localhost:82/api/"
  - url: "http://localhost:83/api/"

tags:
  - name: card
    description: "Взаимодействия с объектом карты"

paths:
  /cards/:
      $ref: ./view/card.yaml
  /cards/{cardId}/:
    $ref: ./view/card.id.yaml
