version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    volumes:
      - ../../routing:/etc/nginx/conf.d
    depends_on:
      - user_service
      - card_service

  frontend:
    build:
      context: ../../
      dockerfile: ./docker/mtg-ladder_instances/dockerfiles/angular.Dockerfile
    volumes:
      - ../../frontend:/usr/src/app/
      - /usr/src/app/node_modules
    command: bash -c "ng serve --host 0.0.0.0 --port 4200"

  card_service_db:
    image: 
      postgres:latest
    restart: 
      always
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_PASSWORD: $CARD_SERVICE_DB_PASS
      POSTGRES_USER: $CARD_SERVICE_DB_USER
      POSTGRES_DB: $CARD_SERVICE_DB_NAME
    volumes:
      - card_service_db:/var/lib/postgresql/data
    ports:
      - "$CARD_SERVICE_DB_PORT:5432"

  card_service:
    build:
        context: ../../
        dockerfile: ./docker/mtg-ladder_instances/dockerfiles/card_service.Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000 && python manage.py migrate"
    volumes:
      - ../../backend/card_service/:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - card_service_db

  user_service_db:
    image:
      postgres:latest
    command: postgres -c listen_addresses='*'
    restart:
      always
    environment:
      POSTGRES_PASSWORD: $USER_SERVICE_DB_PASS
      POSTGRES_USER: $USER_SERVICE_DB_USER
      POSTGRES_DB: $USER_SERVICE_DB_NAME
    volumes:
      - user_service_db:/var/lib/postgresql/data
    ports:
      - "$USER_SERVICE_DB_PORT:5432"

  user_service:
    build:
      context: ../../
      dockerfile: ./docker/mtg-ladder_instances/dockerfiles/user_service.Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000 && python manage.py migrate"
    volumes:
      - ../../backend/user_service/:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - user_service_db
      
volumes:
  user_service_db:
  card_service_db:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: $NETWORK
