# Generated by Django 4.0.3 on 2022-04-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_remove_card_scryfall_id_card_eur_card_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='eur',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='card',
            name='many_faces',
        ),
        migrations.RemoveField(
            model_name='card',
            name='second_image_url',
        ),
        migrations.RemoveField(
            model_name='card',
            name='second_text',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tix',
        ),
        migrations.RemoveField(
            model_name='card',
            name='usd',
        ),
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(default=111, max_length=256),
            preserve_default=False,
        ),
    ]
