# Generated by Django 4.0.3 on 2022-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_remove_card_eur_remove_card_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='english_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='english_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
