# Generated by Django 4.0.3 on 2022-04-07 14:44

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mana_value', models.IntegerField(blank=True, null=True)),
                ('mana_cost', models.CharField(blank=True, max_length=256, null=True)),
                ('colors', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('B', 'Black'), ('G', 'Green'), ('R', 'Red'), ('U', 'Blue'), ('W', 'White')], max_length=9, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Artifact', 'Artifact'), ('Card', 'Card'), ('Conspiracy', 'Conspiracy'), ('Creature', 'Creature'), ('Dragon', 'Dragon'), ('Dungeon', 'Dungeon'), ('Eaturecray', 'Eaturecray'), ('Elemental', 'Elemental'), ('Elite', 'Elite'), ('Emblem', 'Emblem'), ('Enchantment', 'Enchantment'), ('Ever', 'Ever'), ('Goblin', 'Goblin'), ('Hero', 'Hero'), ('Instant', 'Instant'), ('Jaguar', 'Jaguar'), ('Knights', 'Knights'), ('Land', 'Land'), ('Phenomenon', 'Phenomenon'), ('Plane', 'Plane'), ('Planeswalker', 'Planeswalker'), ('Scariest', 'Scariest'), ('Scheme', 'Scheme'), ('See', 'See'), ('Sorcery', 'Sorcery'), ('Specter', 'Specter'), ('Summon', 'Summon'), ('Token', 'Token'), ('Tribal', 'Tribal'), ('Vanguard', 'Vanguard'), ('Wolf', 'Wolf'), ('You’ll', 'You’ll'), ('instant', 'instant')], max_length=254, null=True)),
                ('power', models.CharField(blank=True, max_length=256, null=True)),
                ('toughness', models.CharField(blank=True, max_length=256, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.card')),
            ],
        ),
    ]
