# Generated by Django 4.0.3 on 2022-04-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(default=1111, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardrule',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='restapi.card'),
        ),
    ]
