# Generated by Django 4.0.3 on 2022-04-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_card_scryfall_id_alter_cardrule_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='scryfall_id',
        ),
        migrations.AddField(
            model_name='card',
            name='eur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='many_faces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='second_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='second_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
