name: Backend CI

on:
  push:
    branches: [ main, ignat ]
    paths: [ backend/* ]
  pull_request:
    branches: [ main ]
    paths: [ backend/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_NAME: github_actions
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: 127.0.0.1
      DJANGO_DEBUG: 1
      DJANGO_SECRETKEY: foobar
      DJANGO_LOGGING_LEVEL: DEBUG
      DJANGO_REQUEST_LOGGING_LEVEL: DEBUG
      SMTP_HOST: smtp.yandex.ru
      SMTP_PORT: 465
      SMTP_USE_SSL: 1
    
    services:
      pg_db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Migrate
      run: |
        python backend/manage.py migrate
    - name: Run Tests
      run: |
        python backend/manage.py test
